---
- name: "Install packages"
  hosts: apache
  gather_facts: true
  become: yes
  tasks:

  - name: "Ensure that apache id installed"
      apt:
      #package:
        name:
          - apache2
        state: latest

  - name: "Start Apache"
    service:
      name: apache2
      state: started
      enabled: yes

  - name: "Wait for port 80 to become open jn the host, don't start checking for 10 seconds"
    wait_for: 
      port: 80
      delay: 10

  - name: "Show current IP-address"
    debug:
      msg: "http:// {{ ansible_facts.all_ipv4_addresses[1] }}:80"


# msg: {{ ansible_facts['devices']['xvda']['model']['size']}}
  
  - name: Check that a page return a status 200 and fail if the word Apache is not in the page contents
    ansible.builtin.uri:
      url: http://www.weeww.com
      return_content: true
    register: this
    failed_when: "'Apache' not in this.content"

- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://www.wwewe..com
    

- name: Network info
  vars:
    msg:
      All IP: {{ ansible_all_ipv4_addresses }}
      ALL Interface List: {{ ansible_interfaces }}
  debug:
    mag: "{{ msg.split('\n') }}"
- name: HW info
  vars:
    msg:
      CPU: {{ ansible_processor }}
      CPU Core: {{ ansible_processor_core }}
      RAM: {{ ansible_memtotal_mb}}
      SWAP: {{ ansible_memory_mb.swap.total }}
  debug:
    mag: "{{ msg.split('\n') }}"

