---
- name: Playbook 2 install tuned
  hosts: "apache"
  become: true
  tasks:
  - name: install tuned
    apt:
      name: tuned
      state: present
  - name: starting tuned
    systemd:
      name: tuned
      enabled: true
      masked: no